# Timeout for complete build. Default is 10m.
timeout: 10800s

# The default disk size is 100GB. However, the stage1 ISOs are pretty big these
# days. 200GB  should give us some breathing room.
options:
  diskSizeGb: 400

############################################################################
# BUILD ARTIFACTS
############################################################################

steps:
# Fetch all submodules.
- name: gcr.io/cloud-builders/git
  args: [
    'submodule', 'update', '--init', '--recursive'
  ]

# Create the image builder for later steps.
- name: gcr.io/cloud-builders/docker
  args: [
    'build', '-t', 'epoxy-images-builder', '.'
  ]

# stage1 minimal kernel & initram using stock ubuntu kernel.
- name: epoxy-images-builder
  args: [
    '/workspace/builder.sh', 'stage1_minimal'
  ]
  env:
   - 'PROJECT=$PROJECT_ID'
   - 'ARTIFACTS=/workspace/output'

# stage1 ROMs.
- name: epoxy-images-builder
  args: [
    '/workspace/builder.sh', 'stage1_mlxrom'
  ]
  env:
   - 'PROJECT=$PROJECT_ID'  # One of: mlab-sandbox, mlab-staging, or mlab-oti.
   - 'ARTIFACTS=/workspace/output'

# stage1 ISOs
# NOTE: must run after stage1_minimal so that kernel & initram are available.
- name: epoxy-images-builder
  args: [
    '/workspace/builder.sh', 'stage1_isos'
  ]
  env:
   - 'PROJECT=$PROJECT_ID'
   - 'ARTIFACTS=/workspace/output'
   - 'REGEXP_mlab_sandbox=mlab[1-4].[a-z]{3}[0-9]t.*'
   - 'REGEXP_mlab_staging=mlab4.[a-z]{3}[0-9]{2}.*'
   - 'REGEXP_mlab_oti=mlab[1-3].[a-z]{3}[0-9]{2}.*'

# stage1 USBs
# NOTE: must run after stage1_minimal so that kernel & initram are available.
- name: epoxy-images-builder
  args: [
    '/workspace/builder.sh', 'stage1_usbs'
  ]
  env:
   - 'PROJECT=$PROJECT_ID'
   - 'ARTIFACTS=/workspace/output'
   - 'REGEXP_mlab_sandbox=mlab[1-4].lga1t.*'
   - 'REGEXP_mlab_staging=mlab4.hnd01.*'
   - 'REGEXP_mlab_oti=mlab[1-3].hnd01.*'

############################################################################
# DEPLOY ARTIFACTS
#
# Note: the artifacts built above need to be copied to specific locations in
# the target bucket. Currently, the cloudbuilder 'artifacts' directive does
# not support multiple target locations. So, the steps below are explicit.
############################################################################

# stage1_mlxrom.
- name: gcr.io/cloud-builders/gsutil
  args: [
    '-h', 'Cache-Control:private, max-age=0, no-transform', '-m',
    'cp', '-r', '/workspace/output/stage1_mlxrom/*',
    'gs://epoxy-$PROJECT_ID/stage1_mlxrom/'
  ]

# Deploy stage1_mlxrom images again to the 'latest' directory (without version).
- name: gcr.io/cloud-builders/gsutil
  # NOTE: use bash as the entry point to take advantage of bash file globbing.
  entrypoint: bash
  args:
   - -c
   - >
     gsutil -h "Cache-Control:private, max-age=0, no-transform" -m
     cp -r /workspace/output/stage1_mlxrom/*/*
     gs://epoxy-$PROJECT_ID/stage1_mlxrom/latest/

# stage1_isos.
- name: gcr.io/cloud-builders/gsutil
  args: [
    '-h', 'Cache-Control:private, max-age=0, no-transform', '-m',
    'cp', '-r', '/workspace/output/stage1_isos/*',
    'gs://epoxy-$PROJECT_ID/stage1_isos/'
  ]

# stage1_usbs
- name: gcr.io/cloud-builders/gsutil
  args: [
    '-h', 'Cache-Control:private, max-age=0, no-transform', '-m',
    'cp', '-r', '/workspace/output/stage1_usbs/*',
    'gs://epoxy-$PROJECT_ID/stage1_usbs/'
  ]
