# Timeout for complete build. Default is 10m.
timeout: 7200s

############################################################################
# BUILD ARTIFACTS
############################################################################

steps:
# Create the image builder for later steps.
- name: gcr.io/cloud-builders/docker
  args: [
    'build', '-t', 'epoxy-images-builder', '.'
  ]

# stage1 ROMs.
- name: epoxy-images-builder
  args: [
    '/workspace/builder.sh', 'stage1_mlxrom'
  ]
  env:
   - 'PROJECT=$PROJECT_ID'  # One of: mlab-sandbox, mlab-staging, or mlab-oti.
   - 'ARTIFACTS=/workspace/output'
   - 'MLXROM_VERSION=3.4.809'
   - 'REGEXP_mlab_sandbox=mlab[1-4].[a-z]{3}[0-9]t.*'
   - 'REGEXP_mlab_staging=mlab4.[a-z]{3}[0-9]{2}.*'
   - 'REGEXP_mlab_oti=mlab[1-3].[a-z]{3}[0-9]{2}.*'

# stage1 bootstrapfs.
- name: epoxy-images-builder
  args: [
    '/workspace/builder.sh', 'stage1_bootstrapfs'
  ]
  env:
   - 'PROJECT=$PROJECT_ID'
   - 'ARTIFACTS=/workspace/output'

# stage2 kernel.
- name: epoxy-images-builder
  args: [
    '/workspace/builder.sh', 'stage2'
  ]
  env:
   - 'PROJECT=$PROJECT_ID'
   - 'ARTIFACTS=/workspace/output'

# stage3_coreos images.
- name: epoxy-images-builder
  args: [
    '/workspace/builder.sh', 'stage3_coreos'
  ]
  env:
   - 'PROJECT=$PROJECT_ID'
   - 'ARTIFACTS=/workspace/output'
   - 'COREOS_VERSION=1855.4.0'

# stage3_mlxupdate images.
- name: gcr.io/cloud-builders/gsutil
  args: [
    'cp', 'gs://vendor-mlab-sandbox/mft-4.4.0-44.tgz', '/workspace/vendor'
  ]
- name: epoxy-images-builder
  args: [
    '/workspace/builder.sh', 'stage3_mlxupdate'
  ]
  env:
   - 'PROJECT=$PROJECT_ID'
   - 'ARTIFACTS=/workspace/output'

############################################################################
# DEPLOY ARTIFACTS
#
# Note: the artifacts built above need to be copied to specific locations in
# the target bucket. Currently, the cloudbuilder 'artifacts' directive does
# not support multiple target locations. So, the steps below are explicit.
############################################################################

# stage1_mlxrom.
- name: gcr.io/cloud-builders/gsutil
  args: [
    '-h', 'Cache-Control:private, max-age=0, no-transform',
    'cp', '-r', '/workspace/output/stage1_mlxrom/*',
    'gs://epoxy-$PROJECT_ID/stage1_mlxrom/'
  ]

# stage1_bootstrapfs.
- name: gcr.io/cloud-builders/gsutil
  args: [
    '-h', 'Cache-Control:private, max-age=0, no-transform',
    'cp', '-r', '/workspace/output/bootstrapfs-MeasurementLabUpdate.tar.bz2*',
    'gs://epoxy-$PROJECT_ID/stage1_bootstrapfs/'
  ]

# stage3_coreos.
- name: gcr.io/cloud-builders/gsutil
  args: [
    '-h', 'Cache-Control:private, max-age=0, no-transform',
    'cp', '-r',
    '/workspace/output/stage2_vmlinuz',
    '/workspace/output/coreos_custom_pxe_image.cpio.gz',
    '/workspace/output/coreos_production_pxe.vmlinuz',
    '/workspace/actions/stage2/stage1to2.ipxe',
    '/workspace/actions/stage3_coreos/*.json',
    'gs://epoxy-$PROJECT_ID/stage3_coreos/'
  ]

# stage3_mlxupdate.
- name: gcr.io/cloud-builders/gsutil
  args: [
    '-h', 'Cache-Control:private, max-age=0, no-transform',
    'cp', '-r',
    '/workspace/output/stage2_vmlinuz',
    '/workspace/output/vmlinuz_stage3_mlxupdate',
    '/workspace/output/initramfs_stage3_mlxupdate.cpio.gz',
    '/workspace/actions/stage2/stage1to2.ipxe',
    '/workspace/actions/stage3_mlxupdate/*.json',
    'gs://epoxy-$PROJECT_ID/stage3_mlxupdate/'
  ]
